import { TeamType, BaseID, CellType, WalkwayPosition } from './Constants';

export const INITIAL_GAME_DATA = {
  bases: {
    [BaseID.BASE_1]: { ID: BaseID.BASE_1, coinIDs: ["B1_C1", "B1_C2", "B1_C3", "B1_C4"], color: TeamType.BLUE, nextTurn: BaseID.BASE_2 },
    [BaseID.BASE_2]: { ID: BaseID.BASE_2, coinIDs: ["B2_C1", "B2_C2", "B2_C3", "B2_C4"], color: TeamType.GREEN, nextTurn: BaseID.BASE_4 },
    [BaseID.BASE_3]: { ID: BaseID.BASE_3, coinIDs: ["B3_C1", "B3_C2", "B3_C3", "B3_C4"], color: TeamType.RED, nextTurn: BaseID.BASE_1 },
    [BaseID.BASE_4]: { ID: BaseID.BASE_4, coinIDs: ["B4_C1", "B4_C2", "B4_C3", "B4_C4"], color: TeamType.YELLOW, nextTurn: BaseID.BASE_3 }
  },
  walkways: [
    { ID: "WALKWAY_1", position: WalkwayPosition.NORTH, baseID: BaseID.BASE_2 },
    { ID: "WALKWAY_2", position: WalkwayPosition.EAST, baseID: BaseID.BASE_4 },
    { ID: "WALKWAY_3", position: WalkwayPosition.WEST, baseID: BaseID.BASE_1 },
    { ID: "WALKWAY_4", position: WalkwayPosition.SOUTH, baseID: BaseID.BASE_3 }
  ],
  relationships: [
    { ID: BaseID.BASE_1, type: "BASE" },
    { ID: "WALKWAY_1", type: "WALKWAY" },
    { ID: BaseID.BASE_2, type: "BASE" },
    { ID: "WALKWAY_3", type: "WALKWAY" },
    { ID: "HOME", type: "HOME", baseIDs: [BaseID.BASE_2, BaseID.BASE_4, BaseID.BASE_3, BaseID.BASE_1] },
    { ID: "WALKWAY_2", type: "WALKWAY" },
    { ID: BaseID.BASE_3, type: "BASE" },
    { ID: "WALKWAY_4", type: "WALKWAY" },
    { ID: BaseID.BASE_4, type: "BASE" }
  ],
  // Simplified cells mapping for the engine
  cells: {
    [WalkwayPosition.SOUTH]: {
      "SOUTH_5_0": { baseID: BaseID.BASE_3, cellID: "SOUTH_5_0", col: 0, row: 5, type: CellType.NORMAL },
      "SOUTH_5_1": { baseID: BaseID.BASE_3, cellID: "SOUTH_5_1", col: 1, row: 5, type: CellType.NORMAL },
      "SOUTH_5_2": { baseID: BaseID.BASE_3, cellID: "SOUTH_5_2", col: 2, row: 5, type: CellType.NORMAL },
      "SOUTH_4_0": { baseID: BaseID.BASE_3, cellID: "SOUTH_4_0", col: 0, row: 4, type: CellType.SPAWN },
      "SOUTH_4_1": { baseID: BaseID.BASE_3, cellID: "SOUTH_4_1", col: 1, row: 4, type: CellType.HOMEPATH },
      "SOUTH_4_2": { baseID: BaseID.BASE_3, cellID: "SOUTH_4_2", col: 2, row: 4, type: CellType.NORMAL },
      "SOUTH_3_0": { baseID: BaseID.BASE_3, cellID: "SOUTH_3_0", col: 0, row: 3, type: CellType.NORMAL },
      "SOUTH_3_1": { baseID: BaseID.BASE_3, cellID: "SOUTH_3_1", col: 1, row: 3, type: CellType.HOMEPATH },
      "SOUTH_3_2": { baseID: BaseID.BASE_3, cellID: "SOUTH_3_2", col: 2, row: 3, type: CellType.STAR },
      "SOUTH_2_0": { baseID: BaseID.BASE_3, cellID: "SOUTH_2_0", col: 0, row: 2, type: CellType.NORMAL },
      "SOUTH_2_1": { baseID: BaseID.BASE_3, cellID: "SOUTH_2_1", col: 1, row: 2, type: CellType.HOMEPATH },
      "SOUTH_2_2": { baseID: BaseID.BASE_3, cellID: "SOUTH_2_2", col: 2, row: 2, type: CellType.NORMAL },
      "SOUTH_1_0": { baseID: BaseID.BASE_3, cellID: "SOUTH_1_0", col: 0, row: 1, type: CellType.NORMAL },
      "SOUTH_1_1": { baseID: BaseID.BASE_3, cellID: "SOUTH_1_1", col: 1, row: 1, type: CellType.HOMEPATH },
      "SOUTH_1_2": { baseID: BaseID.BASE_3, cellID: "SOUTH_1_2", col: 2, row: 1, type: CellType.NORMAL },
      "SOUTH_0_0": { baseID: BaseID.BASE_3, cellID: "SOUTH_0_0", col: 0, row: 0, type: CellType.NORMAL },
      "SOUTH_0_1": { baseID: BaseID.BASE_3, cellID: "SOUTH_0_1", col: 1, row: 0, type: CellType.HOMEPATH },
      "SOUTH_0_2": { baseID: BaseID.BASE_3, cellID: "SOUTH_0_2", col: 2, row: 0, type: CellType.NORMAL },
    },
    [WalkwayPosition.WEST]: {
      "WEST_2_5": { baseID: BaseID.BASE_1, cellID: "WEST_2_5", col: 5, row: 2, type: CellType.NORMAL },
      "WEST_2_4": { baseID: BaseID.BASE_1, cellID: "WEST_2_4", col: 4, row: 2, type: CellType.NORMAL },
      "WEST_2_3": { baseID: BaseID.BASE_1, cellID: "WEST_2_3", col: 3, row: 2, type: CellType.NORMAL },
      "WEST_2_2": { baseID: BaseID.BASE_1, cellID: "WEST_2_2", col: 2, row: 2, type: CellType.STAR },
      "WEST_2_1": { baseID: BaseID.BASE_1, cellID: "WEST_2_1", col: 1, row: 2, type: CellType.NORMAL },
      "WEST_2_0": { baseID: BaseID.BASE_1, cellID: "WEST_2_0", col: 0, row: 2, type: CellType.NORMAL },
      "WEST_1_0": { baseID: BaseID.BASE_1, cellID: "WEST_1_0", col: 0, row: 1, type: CellType.NORMAL },
      "WEST_1_1": { baseID: BaseID.BASE_1, cellID: "WEST_1_1", col: 1, row: 1, type: CellType.HOMEPATH },
      "WEST_1_2": { baseID: BaseID.BASE_1, cellID: "WEST_1_2", col: 2, row: 1, type: CellType.HOMEPATH },
      "WEST_1_3": { baseID: BaseID.BASE_1, cellID: "WEST_1_3", col: 3, row: 1, type: CellType.HOMEPATH },
      "WEST_1_4": { baseID: BaseID.BASE_1, cellID: "WEST_1_4", col: 4, row: 1, type: CellType.HOMEPATH },
      "WEST_1_5": { baseID: BaseID.BASE_1, cellID: "WEST_1_5", col: 5, row: 1, type: CellType.HOMEPATH },
      "WEST_0_0": { baseID: BaseID.BASE_1, cellID: "WEST_0_0", col: 0, row: 0, type: CellType.NORMAL },
      "WEST_0_1": { baseID: BaseID.BASE_1, cellID: "WEST_0_1", col: 1, row: 0, type: CellType.SPAWN },
      "WEST_0_2": { baseID: BaseID.BASE_1, cellID: "WEST_0_2", col: 2, row: 0, type: CellType.NORMAL },
      "WEST_0_3": { baseID: BaseID.BASE_1, cellID: "WEST_0_3", col: 3, row: 0, type: CellType.NORMAL },
      "WEST_0_4": { baseID: BaseID.BASE_1, cellID: "WEST_0_4", col: 4, row: 0, type: CellType.NORMAL },
      "WEST_0_5": { baseID: BaseID.BASE_1, cellID: "WEST_0_5", col: 5, row: 0, type: CellType.NORMAL },
    },
    [WalkwayPosition.NORTH]: {
      "NORTH_5_0": { baseID: BaseID.BASE_2, cellID: "NORTH_5_0", col: 0, row: 5, type: CellType.NORMAL },
      "NORTH_4_0": { baseID: BaseID.BASE_2, cellID: "NORTH_4_0", col: 0, row: 4, type: CellType.NORMAL },
      "NORTH_3_0": { baseID: BaseID.BASE_2, cellID: "NORTH_3_0", col: 0, row: 3, type: CellType.NORMAL },
      "NORTH_2_0": { baseID: BaseID.BASE_2, cellID: "NORTH_2_0", col: 0, row: 2, type: CellType.STAR },
      "NORTH_1_0": { baseID: BaseID.BASE_2, cellID: "NORTH_1_0", col: 0, row: 1, type: CellType.NORMAL },
      "NORTH_0_0": { baseID: BaseID.BASE_2, cellID: "NORTH_0_0", col: 0, row: 0, type: CellType.NORMAL },
      "NORTH_0_1": { baseID: BaseID.BASE_2, cellID: "NORTH_0_1", col: 1, row: 0, type: CellType.NORMAL },
      "NORTH_1_1": { baseID: BaseID.BASE_2, cellID: "NORTH_1_1", col: 1, row: 1, type: CellType.HOMEPATH },
      "NORTH_2_1": { baseID: BaseID.BASE_2, cellID: "NORTH_2_1", col: 1, row: 2, type: CellType.HOMEPATH },
      "NORTH_3_1": { baseID: BaseID.BASE_2, cellID: "NORTH_3_1", col: 1, row: 3, type: CellType.HOMEPATH },
      "NORTH_4_1": { baseID: BaseID.BASE_2, cellID: "NORTH_4_1", col: 1, row: 4, type: CellType.HOMEPATH },
      "NORTH_5_1": { baseID: BaseID.BASE_2, cellID: "NORTH_5_1", col: 1, row: 5, type: CellType.HOMEPATH },
      "NORTH_0_2": { baseID: BaseID.BASE_2, cellID: "NORTH_0_2", col: 2, row: 0, type: CellType.NORMAL },
      "NORTH_1_2": { baseID: BaseID.BASE_2, cellID: "NORTH_1_2", col: 2, row: 1, type: CellType.SPAWN },
      "NORTH_2_2": { baseID: BaseID.BASE_2, cellID: "NORTH_2_2", col: 2, row: 2, type: CellType.NORMAL },
      "NORTH_3_2": { baseID: BaseID.BASE_2, cellID: "NORTH_3_2", col: 2, row: 3, type: CellType.NORMAL },
      "NORTH_4_2": { baseID: BaseID.BASE_2, cellID: "NORTH_4_2", col: 2, row: 4, type: CellType.NORMAL },
      "NORTH_5_2": { baseID: BaseID.BASE_2, cellID: "NORTH_5_2", col: 2, row: 5, type: CellType.NORMAL },
    },
    [WalkwayPosition.EAST]: {
      "EAST_0_0": { baseID: BaseID.BASE_4, cellID: "EAST_0_0", col: 0, row: 0, type: CellType.NORMAL },
      "EAST_0_1": { baseID: BaseID.BASE_4, cellID: "EAST_0_1", col: 1, row: 0, type: CellType.NORMAL },
      "EAST_0_2": { baseID: BaseID.BASE_4, cellID: "EAST_0_2", col: 2, row: 0, type: CellType.NORMAL },
      "EAST_0_3": { baseID: BaseID.BASE_4, cellID: "EAST_0_3", col: 3, row: 0, type: CellType.STAR },
      "EAST_0_4": { baseID: BaseID.BASE_4, cellID: "EAST_0_4", col: 4, row: 0, type: CellType.NORMAL },
      "EAST_0_5": { baseID: BaseID.BASE_4, cellID: "EAST_0_5", col: 5, row: 0, type: CellType.NORMAL },
      "EAST_1_5": { baseID: BaseID.BASE_4, cellID: "EAST_1_5", col: 5, row: 1, type: CellType.NORMAL },
      "EAST_1_4": { baseID: BaseID.BASE_4, cellID: "EAST_1_4", col: 4, row: 1, type: CellType.HOMEPATH },
      "EAST_1_3": { baseID: BaseID.BASE_4, cellID: "EAST_1_3", col: 3, row: 1, type: CellType.HOMEPATH },
      "EAST_1_2": { baseID: BaseID.BASE_4, cellID: "EAST_1_2", col: 2, row: 1, type: CellType.HOMEPATH },
      "EAST_1_1": { baseID: BaseID.BASE_4, cellID: "EAST_1_1", col: 1, row: 1, type: CellType.HOMEPATH },
      "EAST_1_0": { baseID: BaseID.BASE_4, cellID: "EAST_1_0", col: 0, row: 1, type: CellType.HOMEPATH },
      "EAST_2_0": { baseID: BaseID.BASE_4, cellID: "EAST_2_0", col: 0, row: 2, type: CellType.NORMAL },
      "EAST_2_1": { baseID: BaseID.BASE_4, cellID: "EAST_2_1", col: 1, row: 2, type: CellType.NORMAL },
      "EAST_2_2": { baseID: BaseID.BASE_4, cellID: "EAST_2_2", col: 2, row: 2, type: CellType.NORMAL },
      "EAST_2_3": { baseID: BaseID.BASE_4, cellID: "EAST_2_3", col: 3, row: 2, type: CellType.NORMAL },
      "EAST_2_4": { baseID: BaseID.BASE_4, cellID: "EAST_2_4", col: 4, row: 2, type: CellType.SPAWN },
      "EAST_2_5": { baseID: BaseID.BASE_4, cellID: "EAST_2_5", col: 5, row: 2, type: CellType.NORMAL },
    }
  },
  links: {
    "SOUTH_4_0": [{ cellID: "SOUTH_3_0", position: WalkwayPosition.SOUTH }],
    "SOUTH_3_0": [{ cellID: "SOUTH_2_0", position: WalkwayPosition.SOUTH }],
    "SOUTH_2_0": [{ cellID: "SOUTH_1_0", position: WalkwayPosition.SOUTH }],
    "SOUTH_1_0": [{ cellID: "SOUTH_0_0", position: WalkwayPosition.SOUTH }],
    "SOUTH_0_0": [{ cellID: "WEST_2_5", position: WalkwayPosition.WEST }],
    "WEST_2_5": [{ cellID: "WEST_2_4", position: WalkwayPosition.WEST }],
    "WEST_2_4": [{ cellID: "WEST_2_3", position: WalkwayPosition.WEST }],
    "WEST_2_3": [{ cellID: "WEST_2_2", position: WalkwayPosition.WEST }],
    "WEST_2_2": [{ cellID: "WEST_2_1", position: WalkwayPosition.WEST }],
    "WEST_2_1": [{ cellID: "WEST_2_0", position: WalkwayPosition.WEST }],
    "WEST_2_0": [{ cellID: "WEST_1_0", position: WalkwayPosition.WEST }],
    "WEST_1_0": [{ cellID: "WEST_0_0", position: WalkwayPosition.WEST }, { cellID: "WEST_1_1", position: WalkwayPosition.WEST }],
    "WEST_1_1": [{ cellID: "WEST_1_2", position: WalkwayPosition.WEST }],
    "WEST_1_2": [{ cellID: "WEST_1_3", position: WalkwayPosition.WEST }],
    "WEST_1_3": [{ cellID: "WEST_1_4", position: WalkwayPosition.WEST }],
    "WEST_1_4": [{ cellID: "WEST_1_5", position: WalkwayPosition.WEST }],
    "WEST_0_0": [{ cellID: "WEST_0_1", position: WalkwayPosition.WEST }],
    "WEST_0_1": [{ cellID: "WEST_0_2", position: WalkwayPosition.WEST }],
    "WEST_0_2": [{ cellID: "WEST_0_3", position: WalkwayPosition.WEST }],
    "WEST_0_3": [{ cellID: "WEST_0_4", position: WalkwayPosition.WEST }],
    "WEST_0_4": [{ cellID: "WEST_0_5", position: WalkwayPosition.WEST }],
    "WEST_0_5": [{ cellID: "NORTH_5_0", position: WalkwayPosition.NORTH }],
    "NORTH_5_0": [{ cellID: "NORTH_4_0", position: WalkwayPosition.NORTH }],
    "NORTH_4_0": [{ cellID: "NORTH_3_0", position: WalkwayPosition.NORTH }],
    "NORTH_3_0": [{ cellID: "NORTH_2_0", position: WalkwayPosition.NORTH }],
    "NORTH_2_0": [{ cellID: "NORTH_1_0", position: WalkwayPosition.NORTH }],
    "NORTH_1_0": [{ cellID: "NORTH_0_0", position: WalkwayPosition.NORTH }],
    "NORTH_0_0": [{ cellID: "NORTH_0_1", position: WalkwayPosition.NORTH }],
    "NORTH_0_1": [{ cellID: "NORTH_0_2", position: WalkwayPosition.NORTH }, { cellID: "NORTH_1_1", position: WalkwayPosition.NORTH }],
    "NORTH_1_1": [{ cellID: "NORTH_2_1", position: WalkwayPosition.NORTH }],
    "NORTH_2_1": [{ cellID: "NORTH_3_1", position: WalkwayPosition.NORTH }],
    "NORTH_3_1": [{ cellID: "NORTH_4_1", position: WalkwayPosition.NORTH }],
    "NORTH_4_1": [{ cellID: "NORTH_5_1", position: WalkwayPosition.NORTH }],
    "NORTH_0_2": [{ cellID: "NORTH_1_2", position: WalkwayPosition.NORTH }],
    "NORTH_1_2": [{ cellID: "NORTH_2_2", position: WalkwayPosition.NORTH }],
    "NORTH_2_2": [{ cellID: "NORTH_3_2", position: WalkwayPosition.NORTH }],
    "NORTH_3_2": [{ cellID: "NORTH_4_2", position: WalkwayPosition.NORTH }],
    "NORTH_4_2": [{ cellID: "NORTH_5_2", position: WalkwayPosition.NORTH }],
    "NORTH_5_2": [{ cellID: "EAST_0_0", position: WalkwayPosition.EAST }],
    "EAST_0_0": [{ cellID: "EAST_0_1", position: WalkwayPosition.EAST }],
    "EAST_0_1": [{ cellID: "EAST_0_2", position: WalkwayPosition.EAST }],
    "EAST_0_2": [{ cellID: "EAST_0_3", position: WalkwayPosition.EAST }],
    "EAST_0_3": [{ cellID: "EAST_0_4", position: WalkwayPosition.EAST }],
    "EAST_0_4": [{ cellID: "EAST_0_5", position: WalkwayPosition.EAST }],
    "EAST_0_5": [{ cellID: "EAST_1_5", position: WalkwayPosition.EAST }],
    "EAST_1_5": [{ cellID: "EAST_2_5", position: WalkwayPosition.EAST }, { cellID: "EAST_1_4", position: WalkwayPosition.EAST }],
    "EAST_1_4": [{ cellID: "EAST_1_3", position: WalkwayPosition.EAST }],
    "EAST_1_3": [{ cellID: "EAST_1_2", position: WalkwayPosition.EAST }],
    "EAST_1_2": [{ cellID: "EAST_1_1", position: WalkwayPosition.EAST }],
    "EAST_1_1": [{ cellID: "EAST_1_0", position: WalkwayPosition.EAST }],
    "EAST_2_5": [{ cellID: "EAST_2_4", position: WalkwayPosition.EAST }],
    "EAST_2_4": [{ cellID: "EAST_2_3", position: WalkwayPosition.EAST }],
    "EAST_2_3": [{ cellID: "EAST_2_2", position: WalkwayPosition.EAST }],
    "EAST_2_2": [{ cellID: "EAST_2_1", position: WalkwayPosition.EAST }],
    "EAST_2_1": [{ cellID: "EAST_2_0", position: WalkwayPosition.EAST }],
    "EAST_2_0": [{ cellID: "SOUTH_0_2", position: WalkwayPosition.SOUTH }],
    "SOUTH_0_2": [{ cellID: "SOUTH_1_2", position: WalkwayPosition.SOUTH }],
    "SOUTH_1_2": [{ cellID: "SOUTH_2_2", position: WalkwayPosition.SOUTH }],
    "SOUTH_2_2": [{ cellID: "SOUTH_3_2", position: WalkwayPosition.SOUTH }],
    "SOUTH_3_2": [{ cellID: "SOUTH_4_2", position: WalkwayPosition.SOUTH }],
    "SOUTH_4_2": [{ cellID: "SOUTH_5_2", position: WalkwayPosition.SOUTH }],
    "SOUTH_5_2": [{ cellID: "SOUTH_5_1", position: WalkwayPosition.SOUTH }],
    "SOUTH_5_1": [{ cellID: "SOUTH_5_0", position: WalkwayPosition.SOUTH }, { cellID: "SOUTH_4_1", position: WalkwayPosition.SOUTH }],
    "SOUTH_5_0": [{ cellID: "SOUTH_4_0", position: WalkwayPosition.SOUTH }],
    "SOUTH_4_1": [{ cellID: "SOUTH_3_1", position: WalkwayPosition.SOUTH }],
    "SOUTH_3_1": [{ cellID: "SOUTH_2_1", position: WalkwayPosition.SOUTH }],
    "SOUTH_2_1": [{ cellID: "SOUTH_1_1", position: WalkwayPosition.SOUTH }],
    "SOUTH_1_1": [{ cellID: "SOUTH_0_1", position: WalkwayPosition.SOUTH }],
    "SOUTH_0_1": [{ cellID: "HOME", position: "HOME" }],
    "EAST_1_0": [{ cellID: "HOME", position: "HOME" }],
    "NORTH_5_1": [{ cellID: "HOME", position: "HOME" }],
    "WEST_1_5": [{ cellID: "HOME", position: "HOME" }]
  }
};
